### ISSUE TITLE
Podziekowanie - wydawnictwo?

### ISSUE THREAD

**Issue by Iwona007** [bykowski/livebook#11]
To chyba nie dokońca feature . Zastanawialam się nad tym. Na stronie książki jest info że gdy ktoś kupuje ksiązkę i pree book to może otrzymać specjalne podziekowanie. W niektórych ksiazkach są podzieńkowania autorów. Może też dodać na początku ksiązki dla kogoś, np wydawnictwo. Też troche go szukałeś i pertraktacje pewnie też trochę trwały, więc może warto ze względu na współprace i kolejne edycje.

**Comment by bykowski** [comment]
Tu masz na myśli specjalne podziękowanie dla konkretnego Czytelnika? Czy jakby miało to wyglądać? Możesz podać przykładowy case scenario?

**Comment by Iwona007** [comment]
Tak, ponieżej zamieszczam przykłady. Pierwszy case z ksiażki z Oracla, drugi z Javy, trzeci - Spring w Akcji.  Te przykłday są różne bo to zależy czy Autor chce wzboadzić swoją ksiązkę o coś takiego, i co chce tam napisać i do kogo chce napisać od siebie. Więc odpowiadając na pytanie czy dla konkretnego Czytelnika - to zleży: do kogo Autor chce to skierować czy do jednej osoby, czy do kilku, czy do grupy, albo do kilku grup. Więc mam taki oglólny pomysł, ale to Ty wspołpracujesz przy tym z wieloma ludzmi, więc masz pogląd na cały przebieg tworzenia książki i współpracy, tak dalej. Potencjalny czytenik też będzie wpierał książke, kupijąc czytając, pózniej polecając. **Gdyby to miało być dla przyszłego czytelnika,** to można by podziękować za zaufanie do materiałów, wybór tej pozycji, że ma się nadzieje że spełni oczekiwania, a co najwżniejsze uławi zrozumienie.  Więc to też zależy z której strony na to spojrzeć, można zrobić combo i spojrzeć na to wielowymiarowo. Mam nadzije że udało mi się rzucić nieco światła na sprawę. 
![case_scenario_3](https://user-images.githubusercontent.com/51120038/126876048-78738834-d150-488c-84c5-d648fd41454c.jpg)
![case scenario_1](https://user-images.githubusercontent.com/51120038/126875600-060caf58-bd50-4cfe-92
![case_scenario_2](https://user-images.githubusercontent.com/51120038/126875616-907cab54-cc14-419f-bb01-138e04468a0e.jpg)
5f-50f2eaa5f379.jpg)
![case_scenario_3](https://user-images.githubusercontent.com/51120038/126876048-78738834-d150-488c-84c5-d648fd41454c.jpg)
