### ISSUE TITLE
Błąd 404 w hello-api

### ISSUE THREAD

**Issue by P0rtier** [bykowski/livebook#19]
Na stronach 61-62 znajduje się przykład połączenia z adresem https://livebooks.pl/materials/v1/hello-api w celu sprawdzenia metody webowej, aczkolwiek pod wskazanym adresem wyskakuje błąd 404.
Przeglądarka:
![404Chrome](https://user-images.githubusercontent.com/83017833/202756384-41ac2b2b-8dc6-474b-9746-701d369bc5d7.PNG)
Postman:
![404Postman](https://user-images.githubusercontent.com/83017833/202756824-227fea0d-22f9-4dc0-b3d8-43f2669f3999.PNG)

**Comment by bykowski** [comment]
Dziękuje @P0rtier za zgłoszenie! Już naprawione, czekam na info od Ciebie - czy mogę zamknąć zgłoszenie 🤗

**Comment by P0rtier** [comment]
Dzięki za szybką odpowiedź! :D
