### ISSUE TITLE
Strona 30, 34  - grafiki mało czytelne

### ISSUE THREAD

**Issue by marcinPluciennik** [bykowski/livebook#8]
Grafika na stronie 30, 34 jest mało czytelna. Czcionka jest za mała, nie da się przeczytać napisów. Może dać ją wertykalnie?

**Comment by bykowski** [comment]
Dzięki Marcin za zgłoszenie, tak jak jest to opisane na stronie głównej z ticketami to formatowania nie trzeba na tym etapie zgłaszać, będzie ono zmieniane :)
Cieszę się, że się angażujesz! Czekam na Twoje kolejne zgłoszenia :)
